In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

In [2]:
import os

path = r"C:\Users\PRAJYOT\OneDrive\Desktop\uidai projrct"
os.path.exists(path)

True

In [3]:
import os
import pandas as pd

BASE_PATH = r"C:\Users\PRAJYOT\OneDrive\Desktop\uidai projrct"

enrolment_files = [
    os.path.join(BASE_PATH, "api_data_aadhar_enrolment_0_500000.csv"),
    os.path.join(BASE_PATH, "api_data_aadhar_enrolment_500000_1000000.csv"),
 os.path.join(BASE_PATH, "api_data_aadhar_enrolment_1000000_1006029.csv")
]
# Test first file
pd.read_csv(enrolment_files[0]).head()

         date          state          district  pincode  age_0_5  age_5_17  age_18_greater
0  02-03-2025      Meghalaya  East Khasi Hills   793121       11        61              37
1  09-03-2025      Karnataka   Bengaluru Urban   560043       14        33              39
2  09-03-2025  Uttar Pradesh      Kanpur Nagar   208001       29        82              12
3  09-03-2025  Uttar Pradesh           Aligarh   202133       62        29              15
4  09-03-2025      Karnataka   Bengaluru Urban   560016       14        16              21

In [4]:
enrol_df = pd.concat(
    [pd.read_csv(f) for f in enrolment_files],
    ignore_index=True
)
print("ENROLMENT DATA SHAPE:", enrol_df.shape)
display(enrol_df.head())

ENROLMENT DATA SHAPE: (1006029, 7)

         date          state          district  pincode  age_0_5  age_5_17  age_18_greater
0  02-03-2025      Meghalaya  East Khasi Hills   793121       11        61              37
1  09-03-2025      Karnataka   Bengaluru Urban   560043       14        33              39
2  09-03-2025  Uttar Pradesh      Kanpur Nagar   208001       29        82              12
3  09-03-2025  Uttar Pradesh           Aligarh   202133       62        29              15
4  09-03-2025      Karnataka   Bengaluru Urban   560016       14        16              21

In [5]:
# -------- DEMOGRAPHIC DATA --------
demo_files = [
    os.path.join(BASE_PATH, "api_data_aadhar_demographic_0_500000.csv"),
    os.path.join(BASE_PATH, "api_data_aadhar_demographic_500000_1000000.csv"),
    os.path.join(BASE_PATH, "api_data_aadhar_demographic_1000000_1500000.csv"),
    os.path.join(BASE_PATH, "api_data_aadhar_demographic_2000000_2071700.csv")
]

# Test first demographic file
pd.read_csv(demo_files[0]).head()

         date           state    district  pincode  demo_age_5_17  demo_age_17_
0  01-03-2025   Uttar Pradesh   Gorakhpur   273213             49           529
1  01-03-2025  Andhra Pradesh    Chittoor   517132             22           375
2  01-03-2025         Gujarat      Rajkot   360006             65           765
3  01-03-2025  Andhra Pradesh  Srikakulam   532484             24           314
4  01-03-2025       Rajasthan     Udaipur   313801             45           785

In [6]:
# -------- BIOMETRIC DATA --------
bio_files = [
    os.path.join(BASE_PATH, "api_data_aadhar_biometric_0_500000.csv"),
    os.path.join(BASE_PATH, "api_data_aadhar_biometric_500000_1000000.csv"),
    os.path.join(BASE_PATH, "api_data_aadhar_biometric_1000000_1500000.csv")
]

# Test first biometric file
pd.read_csv(bio_files[0]).head()

         date              state      district  pincode  bio_age_5_17  bio_age_17_
0  01-03-2025            Haryana  Mahendragarh   123029           280          577
1  01-03-2025              Bihar     Madhepura   852121           144          369
2  01-03-2025  Jammu and Kashmir         Punch   185101           643         1091
3  01-03-2025              Bihar       Bhojpur   802158           256          980
4  01-03-2025         Tamil Nadu       Madurai   625514           271          815

In [7]:
enrol_df = pd.concat([pd.read_csv(f) for f in enrolment_files], ignore_index=True)
demo_df  = pd.concat([pd.read_csv(f) for f in demo_files], ignore_index=True)
bio_df   = pd.concat([pd.read_csv(f) for f in bio_files], ignore_index=True)

In [8]:
print("DEMOGRAPHIC DATA SHAPE:", demo_df.shape)
display(demo_df.head())

DEMOGRAPHIC DATA SHAPE: (1571700, 6)

         date           state    district  pincode  demo_age_5_17  demo_age_17_
0  01-03-2025   Uttar Pradesh   Gorakhpur   273213             49           529
1  01-03-2025  Andhra Pradesh    Chittoor   517132             22           375
2  01-03-2025         Gujarat      Rajkot   360006             65           765
3  01-03-2025  Andhra Pradesh  Srikakulam   532484             24           314
4  01-03-2025       Rajasthan     Udaipur   313801             45           785

In [9]:
print("BIOMETRIC DATA SHAPE:", bio_df.shape)
display(bio_df.head())

BIOMETRIC DATA SHAPE: (1500000, 6)

         date              state      district  pincode  bio_age_5_17  bio_age_17_
0  01-03-2025            Haryana  Mahendragarh   123029           280          577
1  01-03-2025              Bihar     Madhepura   852121           144          369
2  01-03-2025  Jammu and Kashmir         Punch   185101           643         1091
3  01-03-2025              Bihar       Bhojpur   802158           256          980
4  01-03-2025         Tamil Nadu       Madurai   625514           271          815

In [10]:
def clean_region_names(df):
    for col in ["state", "district"]:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip().str.title()
    return df

In [11]:
def add_year_column(df):
    df["date"] = pd.to_datetime(df["date"], dayfirst=True, errors="coerce")
    df["year"] = df["date"].dt.year
    return df

In [12]:
enrol_df = clean_region_names(enrol_df)
demo_df = clean_region_names(demo_df)
bio_df = clean_region_names(bio_df)

enrol_df = add_year_column(enrol_df)
demo_df = add_year_column(demo_df)
bio_df = add_year_column(bio_df)

enrol_df.drop_duplicates(inplace=True)
demo_df.drop_duplicates(inplace=True)
bio_df.drop_duplicates(inplace=True)

In [13]:
print(enrol_df.columns.tolist())

['date', 'state', 'district', 'pincode', 'age_0_5', 'age_5_17', 'age_18_greater', 'year']

In [14]:
enrol_yearly = enrol_df.groupby(
    "year", as_index=False
)[["age_5_17", "age_18_greater"]].sum()

enrol_long = enrol_yearly.melt(
    id_vars="year",
    var_name="age_group",
    value_name="enrolment_count"
)

enrol_long["age_group"] = enrol_long["age_group"].map({
    "age_5_17": "Age 5–17",
    "age_18_greater": "Age 18+"
})

In [15]:
print(enrol_long.head())
print(enrol_long.isna().sum())

   year age_group  enrolment_count
0  2025  Age 5–17          1690892
1  2025   Age 18+           166462
year               0
age_group          0
enrolment_count    0
dtype: int64

In [16]:
fig_enrol = px.line(
    enrol_long,
    x="year",
    y="enrolment_count",
    color="age_group",
    markers=True,
    title="Aadhaar Enrolment Growth by Age Group"
)
fig_enrol.show()

In [17]:
print(bio_df.columns.tolist())

['date', 'state', 'district', 'pincode', 'bio_age_5_17', 'bio_age_17_', 'year']

In [18]:
bio_yearly = bio_df.groupby(
    "year", as_index=False
)[["bio_age_5_17", "bio_age_17_"]].sum()

bio_long = bio_yearly.melt(
    id_vars="year",
    var_name="age_group",
    value_name="biometric_usage"
)

bio_long["age_group"] = bio_long["age_group"].map({
    "bio_age_5_17": "Age 5–17",
    "bio_age_17_": "Age 17+"
})

In [19]:
fig_bio = px.line(
    bio_long,
    x="year",
    y="biometric_usage",
    color="age_group",
    markers=True,
    title="Aadhaar Biometric Usage Growth by Age Group"
)
fig_bio.show()

In [20]:
common_age_groups = ["Age 5–17", "Age 17+"]

enrol_aligned = enrol_long[enrol_long["age_group"].isin(common_age_groups)]
bio_aligned = bio_long[bio_long["age_group"].isin(common_age_groups)]

In [21]:
enrol_compare = enrol_long.rename(columns={"enrolment_count": "value"})
enrol_compare["type"] = "Enrolment"

bio_compare = bio_long.rename(columns={"biometric_usage": "value"})
bio_compare["type"] = "Biometric Usage"

gap_df = pd.concat([enrol_compare, bio_compare], ignore_index=True)

In [22]:
fig_gap = px.line(
    gap_df,
    x="year",
    y="value",
    color="type",
    facet_col="age_group",
    markers=True,
    title="Enrolment vs Biometric Usage (Log Scale)"
)

fig_gap.update_yaxes(type="log")
fig_gap.show()

In [23]:
state_year_age = enrol_df.groupby(
    ["state", "year"], as_index=False
)[["age_5_17", "age_18_greater"]].sum()

state_long = state_year_age.melt(
    id_vars=["state", "year"],
    var_name="age_group",
    value_name="enrolment_count"
)

state_long["age_group"] = state_long["age_group"].map({
    "age_5_17": "Age 5–17",
    "age_18_greater": "Age 18+"
})

In [24]:
fig_state = px.bar(
    state_long,
    x="enrolment_count",
    y="state",
    color="age_group",
    animation_frame="year",
    orientation="h",
    title="State-wise Aadhaar Enrolment Race (Age-wise)",
    height=650
)

fig_state.update_layout(
    xaxis_title="Total Enrolments",
    yaxis_title="State",
    showlegend=True
)

fig_state.show()

In [25]:
heat_df = state_long.groupby(
    ["state", "year"], as_index=False
)["enrolment_count"].sum()

fig_state = px.density_heatmap(
    heat_df,
    x="year",
    y="state",
    z="enrolment_count",
    color_continuous_scale="Viridis",
    title="State-wise Aadhaar Enrolment Intensity"
)

fig_state.show()

In [26]:
enrol_long = enrol_long.sort_values(["age_group", "year"])

enrol_long["yoy_growth_pct"] = enrol_long.groupby(
    "age_group"
)["enrolment_count"].pct_change() * 100

anomalies = enrol_long[
    enrol_long["yoy_growth_pct"].abs() > 30
]

print("ANOMALIES (YoY Change > 30%)")
display(anomalies)

ANOMALIES (YoY Change > 30%)

Empty DataFrame
Columns: [year, age_group, enrolment_count, yoy_growth_pct]
Index: []

In [27]:
usage_index = gap_df.pivot_table(
    index=["year", "age_group"],
    columns="type",
    values="value",
    aggfunc="sum"
).reset_index()

usage_index["usage_per_enrolment"] = (
    usage_index["Biometric Usage"] /
    usage_index["Enrolment"]
)

fig = px.line(
    usage_index,
    x="year",
    y="usage_per_enrolment",
    color="age_group",
    markers=True,
    title="Aadhaar Usage Intensity Index (Usage per Enrolment)"
)

fig.show()

In [28]:
cum_df = enrol_long.copy()
cum_df["cumulative"] = cum_df.groupby(
    "age_group"
)["enrolment_count"].cumsum()

fig = px.area(
    cum_df,
    x="year",
    y="cumulative",
    color="age_group",
    title="Cumulative Aadhaar Enrolment Penetration"
)

fig.show()

In [29]:
india_map_df = state_long.groupby(
    ["state", "age_group"], as_index=False
)["enrolment_count"].sum()

In [6]:
import plotly.express as px

fig = px.choropleth(
    india_map_df,
    geojson="https://raw.githubusercontent.com/geohacker/india/master/state/india_telengana.geojson",
    featureidkey="properties.NAME_1",
    locations="state",
    color="enrolment_count",
    color_continuous_scale="YlOrRd",
    title="India Heatmap: Aadhaar Enrolment Intensity (State-wise)",
    labels={"enrolment_count": "Total Enrolments"}
)

fig.update_geos(
    fitbounds="locations",
    visible=False
)

fig.update_layout(
    margin={"r":0,"t":50,"l":0,"b":0},
    coloraxis_colorbar=dict(title="Enrolments")
)

fig.show()

india_map_df["state"] = india_map_df["state"].replace({
    "Orissa": "Odisha",
    "Delhi": "NCT of Delhi"
})

In [ ]:
import plotly.express as px

map_year_df = state_long.copy()

# Use the full India states GeoJSON instead of Telangana-only
fig = px.choropleth(
    map_year_df,
    geojson="https://raw.githubusercontent.com/geohacker/india/master/state/india.geojson",
    featureidkey="properties.NAME_1",  # matches state names in the GeoJSON
    locations="state",                 # your dataframe column with state names
    color="enrolment_count",
    animation_frame="year",
    color_continuous_scale="Plasma",
    title="India Aadhaar Enrolment Growth Over Time"
)

fig.update_geos(fitbounds="locations", visible=False)
fig.show()

NameError: name 'state_long' is not defined

In [32]:
print("="*80)
print("KEY FINDINGS")
print("="*80)

print("\n1. Adult Aadhaar (Age 17+) drives overall enrolment and biometric usage.")
print("   - Majority of enrolments and almost all biometric authentications come from adults.")

print("\n2. Youth Aadhaar (Age 5–17) shows high enrolment but low biometric usage.")
print("   - Indicates Aadhaar is used mainly as an identity record for youth.")

print("\n3. Children below Age 5 have negligible biometric usage.")
print("   - Biometric authentication is not feasible for this age group.")

print("\n4. Enrolment growth shows sudden year-on-year spikes.")
print("   - Suggests campaign-driven or policy-driven enrolment phases.")

print("\n5. Strong regional inequality exists across states.")
print("   - A few states contribute disproportionately to total enrolment.")

print("\n6. Aadhaar adoption is approaching maturity.")
print("   - Growth rate stabilizes over time following an S-curve pattern.")


print("\n" + "="*80)
print("RECOMMENDATIONS")
print("="*80)

print("\n1. Shift focus from enrolment numbers to Aadhaar usage intensity.")
print("   - Measure success using authentication and service usage metrics.")

print("\n2. Introduce targeted Aadhaar usage programs for Age 5–17.")
print("   - Integrate Aadhaar with education, scholarships, and health services.")

print("\n3. Use non-biometric or guardian-based authentication for children below 5.")
print("   - Aadhaar should act as a linking identity rather than an authentication tool.")

print("\n4. Design region-specific Aadhaar strategies.")
print("   - Use state-wise heatmaps to identify low-performing regions.")

print("\n5. Audit anomaly years with abnormal enrolment growth.")
print("   - Helps assess effectiveness of government initiatives.")

print("\n6. Scale biometric infrastructure for adult-heavy usage patterns.")
print("   - Focus capacity planning on high-usage states.")


print("\n" + "="*80)
print("CONCLUSION")
print("="*80)

print(
    "\nThis analysis shows that Aadhaar has transitioned from a rapid enrolment phase "
    "to a maturity stage where usage effectiveness and regional equity are critical. "
    "Focusing on usage intensity, age-specific strategies, and regional targeting "
    "will significantly enhance the real-world impact of Aadhaar."
)

print("\n" + "="*80)

================================================================================
KEY FINDINGS
================================================================================

1. Adult Aadhaar (Age 17+) drives overall enrolment and biometric usage.
   - Majority of enrolments and almost all biometric authentications come from adults.

2. Youth Aadhaar (Age 5–17) shows high enrolment but low biometric usage.
   - Indicates Aadhaar is used mainly as an identity record for youth.

3. Children below Age 5 have negligible biometric usage.
   - Biometric authentication is not feasible for this age group.

4. Enrolment growth shows sudden year-on-year spikes.
   - Suggests campaign-driven or policy-driven enrolment phases.

5. Strong regional inequality exists across states.
   - A few states contribute disproportionately to total enrolment.

6. Aadhaar adoption is approaching maturity.
   - Growth rate stabilizes over time following an S-curve pattern.

================================================================================
RECOMMENDATIONS
================================================================================

1. Shift focus from enrolment numbers to Aadhaar usage intensity.
   - Measure success using authentication and service usage metrics.

2. Introduce targeted Aadhaar usage programs for Age 5–17.
   - Integrate Aadhaar with education, scholarships, and health services.

3. Use non-biometric or guardian-based authentication for children below 5.
   - Aadhaar should act as a linking identity rather than an authentication tool.

4. Design region-specific Aadhaar strategies.
   - Use state-wise heatmaps to identify low-performing regions.

5. Audit anomaly years with abnormal enrolment growth.
   - Helps assess effectiveness of government initiatives.

6. Scale biometric infrastructure for adult-heavy usage patterns.
   - Focus capacity planning on high-usage states.

================================================================================
CONCLUSION
================================================================================

This analysis shows that Aadhaar has transitioned from a rapid enrolment phase to a maturity stage where usage effectiveness and regional equity are critical. Focusing on usage intensity, age-specific strategies, and regional targeting will significantly enhance the real-world impact of Aadhaar.

================================================================================

In [33]:
enrolment_trends = enrol_long.copy()
age_group_df = enrol_long.copy()
state_df = state_long.copy()

enrolment_trends.to_csv("enrolment_trends.csv", index=False)
age_group_df.to_csv("age_group_analysis.csv", index=False)
state_df.to_csv("state_wise_data.csv", index=False)

In [34]:
pd.read_csv("enrolment_trends.csv").head()
pd.read_csv("age_group_analysis.csv").head()
pd.read_csv("state_wise_data.csv").head()

                         state  year age_group  enrolment_count
0                       100000  2025  Age 5–17                1
1    Andaman & Nicobar Islands  2025  Age 5–17                5
2  Andaman And Nicobar Islands  2025  Age 5–17               27
3               Andhra Pradesh  2025  Age 5–17            13414
4            Arunachal Pradesh  2025  Age 5–17             2176

In [35]:
state_total_df = state_long.groupby(
    "state", as_index=False
)["enrolment_count"].sum()

state_total_df.to_csv("state_total_enrolment.csv", index=False)